Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController",
            "name": "BasketController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-BasketController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020the\u0020resource.",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003AindexSeller\u0028\u0029",
            "name": "indexSeller",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020baskets\u0020for\u0020the\u0020current\u0020seller",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_indexSeller"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003AgetBasketSeller\u0028\u0029",
            "name": "getBasketSeller",
            "summary": "Returns\u0020a\u0020basket\u0020\u0028if\u0020seller\u0020has\u0020access\u0020to\u0020it\u0029",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_getBasketSeller"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003AupdateBasketSeller\u0028\u0029",
            "name": "updateBasketSeller",
            "summary": "Allow\u0020the\u0020seller\u0020to\u0020update\u0020basket\u0020status",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_updateBasketSeller"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003AaddProduct\u0028\u0029",
            "name": "addProduct",
            "summary": "Creates\u0020an\u0020item\u0020and\u0020adds\u0020it\u0020to\u0020the\u0020basket",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_addProduct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003AgetComment\u0028\u0029",
            "name": "getComment",
            "summary": "Returns\u0020the\u0020comment\u0020for\u0020a\u0020user\/shop.\u0020This\u0020comment\u0020will\u0020belong\u0020to\u0020an\u0020unconfirmed\u0020basket.\u0020If\u0020the\u0020user\u0020has\nno\u0020unconfirmed\u0020basket\u0020for\u0020the\u0020shop,\u0020the\u0020basket\u0020will\u0020be\u0020created\u0020with\u0020an\u0020empty\u0020message.",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_getComment"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003ApostComment\u0028\u0029",
            "name": "postComment",
            "summary": "Replaces\u0020the\u0020comment\u0020in\u0020an\u0020unconfirmed\u0020basket\u0020for\u0020a\u0020user.\u0020If\u0020the\u0020user\u0020has\u0020no\u0020unconfirmed\u0020basket\u0020for\u0020the\nshop,\u0020it\u0020will\u0020be\u0020created\u0020and\u0020the\u0020message\u0020attatched\u0020to\u0020it.",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_postComment"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003Aconfirm\u0028\u0029",
            "name": "confirm",
            "summary": "Confirms\u0020de\u0020basket\u0020to\u0020be\u0020prepared\u0020by\u0020shop",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_confirm"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003AitemConfirm\u0028\u0029",
            "name": "itemConfirm",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_itemConfirm"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003AitemUpdate\u0028\u0029",
            "name": "itemUpdate",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_itemUpdate"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003AshopsBaskets\u0028\u0029",
            "name": "shopsBaskets",
            "summary": "Returns\u0020all\u0020baskets\u0020for\u0020a\u0020client",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_shopsBaskets"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\BasketController\u003A\u003AitemsSeller\u0028\u0029",
            "name": "itemsSeller",
            "summary": "Returns\u0020items\u0020of\u0020a\u0020basket,\u0020if\u0020current\u0020user\u0020is\u0020a\u0020seller\u0020and\u0020has\u0020access\u0020to\u0020them",
            "url": "classes/App-Http-Controllers-Api-BasketController.html#method_itemsSeller"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\MarketController",
            "name": "MarketController",
            "summary": "It\u0020allows\u0020to\u0020create,\u0020list\u0020and\u0020show\u0020markets",
            "url": "classes/App-Http-Controllers-Api-MarketController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\MarketController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020Markets",
            "url": "classes/App-Http-Controllers-Api-MarketController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\MarketController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Returns\u0020a\u0020Market\u0020with\u0020all\u0020data\u0020necessary\u0020to\u0020show\u0020it",
            "url": "classes/App-Http-Controllers-Api-MarketController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\MarketController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Stores\u0020a\u0020Market\u0020and\u0020returns\u0020it",
            "url": "classes/App-Http-Controllers-Api-MarketController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductController",
            "name": "ProductController",
            "summary": "Allow\u0020to\u0020create,\u0020list,\u0020update\u0020and\u0020destroy\u0020Products",
            "url": "classes/App-Http-Controllers-Api-ProductController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "List\u0020all\u0020products\u0020for\u0020a\u0020shop",
            "url": "classes/App-Http-Controllers-Api-ProductController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Stores\u0020a\u0020new\u0020product,\u0020after\u0020checking\u0020the\u0020user\u0020has\u0020access\u0020to\u0020the\u0020shop.",
            "url": "classes/App-Http-Controllers-Api-ProductController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020a\u0020product",
            "url": "classes/App-Http-Controllers-Api-ProductController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Deletes\u0020a\u0020product",
            "url": "classes/App-Http-Controllers-Api-ProductController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductController\u003A\u003AmapUnits\u0028\u0029",
            "name": "mapUnits",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-ProductController.html#method_mapUnits"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductSellerController",
            "name": "ProductSellerController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-ProductSellerController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductSellerController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "List\u0020sellers\u0020productes.\u0020It\u0020accept\u0020a\u0020shop_id\u0020as\u0020a\u0020parameter\u0020to\u0020filter\u0020just\u0020one\u0020shop",
            "url": "classes/App-Http-Controllers-Api-ProductSellerController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductSellerController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-Api-ProductSellerController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductSellerController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-Api-ProductSellerController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductSellerController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-Api-ProductSellerController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductSellerController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-Api-ProductSellerController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductSellerController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-Api-ProductSellerController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ProductSellerController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-Api-ProductSellerController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ShopController",
            "name": "ShopController",
            "summary": "Controler\u0020for\u0020Shop\u0020model",
            "url": "classes/App-Http-Controllers-Api-ShopController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ShopController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Returns\u0020all\u0020shops,\u0020or\u0020filtered\u0020by\u0020market_id\u0020if\u0020present",
            "url": "classes/App-Http-Controllers-Api-ShopController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ShopController\u003A\u003AindexSeller\u0028\u0029",
            "name": "indexSeller",
            "summary": "Returns\u0020shops\u0020whose\u0020current\u0020user\u0020is\u0020the\u0020owner",
            "url": "classes/App-Http-Controllers-Api-ShopController.html#method_indexSeller"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ShopController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Creates\u0020a\u0020new\u0020Shop",
            "url": "classes/App-Http-Controllers-Api-ShopController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ShopController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020a\u0020Shop",
            "url": "classes/App-Http-Controllers-Api-ShopController.html#method_delete"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\ShopController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Returns\u0020a\u0020Shop\u0020by\u0020id",
            "url": "classes/App-Http-Controllers-Api-ShopController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UnitController",
            "name": "UnitController",
            "summary": "Controller\u0020for\u0020Unit\u0020model",
            "url": "classes/App-Http-Controllers-Api-UnitController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UnitController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "List\u0020all\u0020Units",
            "url": "classes/App-Http-Controllers-Api-UnitController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UnitController\u003A\u003AgetBySymbol\u0028\u0029",
            "name": "getBySymbol",
            "summary": "Returns\u0020the\u0020Unit\u0020with\u0020\u0024symbol",
            "url": "classes/App-Http-Controllers-Api-UnitController.html#method_getBySymbol"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UnitController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Stores\u0020a\u0020Unit",
            "url": "classes/App-Http-Controllers-Api-UnitController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UnitController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020a\u0020Unit",
            "url": "classes/App-Http-Controllers-Api-UnitController.html#method_delete"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UserController",
            "name": "UserController",
            "summary": "User\u0020controller\u0020for\u0020API\u0020calls",
            "url": "classes/App-Http-Controllers-Api-UserController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UserController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020the\u0020resource.",
            "url": "classes/App-Http-Controllers-Api-UserController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UserController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Show\u0020the\u0020form\u0020for\u0020creating\u0020a\u0020new\u0020resource.",
            "url": "classes/App-Http-Controllers-Api-UserController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UserController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020newly\u0020created\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-Api-UserController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UserController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Display\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-Api-UserController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UserController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Show\u0020the\u0020form\u0020for\u0020editing\u0020the\u0020specified\u0020resource.",
            "url": "classes/App-Http-Controllers-Api-UserController.html#method_edit"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UserController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020resource\u0020in\u0020storage.",
            "url": "classes/App-Http-Controllers-Api-UserController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\UserController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Remove\u0020the\u0020specified\u0020resource\u0020from\u0020storage.",
            "url": "classes/App-Http-Controllers-Api-UserController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ConfirmPasswordController",
            "name": "ConfirmPasswordController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-ConfirmPasswordController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ConfirmPasswordController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-Auth-ConfirmPasswordController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ConfirmPasswordController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020when\u0020the\u0020intended\u0020url\u0020fails.",
            "url": "classes/App-Http-Controllers-Auth-ConfirmPasswordController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ForgotPasswordController",
            "name": "ForgotPasswordController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-ForgotPasswordController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ForgotPasswordController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-Auth-ForgotPasswordController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ForgotPasswordController\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-ForgotPasswordController.html#method___invoke"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController",
            "name": "LoginController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003Aauthenticated\u0028\u0029",
            "name": "authenticated",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#method_authenticated"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003AloggedOut\u0028\u0029",
            "name": "loggedOut",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#method_loggedOut"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020after\u0020login.",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController",
            "name": "RegisterController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003Avalidator\u0028\u0029",
            "name": "validator",
            "summary": "Get\u0020a\u0020validator\u0020for\u0020an\u0020incoming\u0020registration\u0020request.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#method_validator"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020user\u0020instance\u0020after\u0020a\u0020valid\u0020registration.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#method_create"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003Aregistered\u0028\u0029",
            "name": "registered",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#method_registered"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020after\u0020registration.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ResetPasswordController",
            "name": "ResetPasswordController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-ResetPasswordController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\ResetPasswordController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020after\u0020resetting\u0020their\u0020password.",
            "url": "classes/App-Http-Controllers-Auth-ResetPasswordController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\VerificationController",
            "name": "VerificationController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-VerificationController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\VerificationController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-Auth-VerificationController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\VerificationController\u003A\u003A\u0024redirectTo",
            "name": "redirectTo",
            "summary": "Where\u0020to\u0020redirect\u0020users\u0020after\u0020verification.",
            "url": "classes/App-Http-Controllers-Auth-VerificationController.html#property_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController",
            "name": "AuthController",
            "summary": "Controller\u0020for\u0020Auth\u0020calls",
            "url": "classes/App-Http-Controllers-AuthController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Registers\u0020a\u0020new\u0020user\u0020and\u0020automatically\u0020login\u0020returning\u0020the\u0020token",
            "url": "classes/App-Http-Controllers-AuthController.html#method_register"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Login\u0020the\u0020user\u0020and\u0020returns\u0020a\u0020valid\u0020token\u0020for\u0020nexts\u0020api\u0020calls",
            "url": "classes/App-Http-Controllers-AuthController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Logout\u0020current\u0020user,\u0020invalidating\u0020its\u0020token.",
            "url": "classes/App-Http-Controllers-AuthController.html#method_logout"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Ame\u0028\u0029",
            "name": "me",
            "summary": "Returns\u0020logged\u0020user\u0020info",
            "url": "classes/App-Http-Controllers-AuthController.html#method_me"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020user\u0020info",
            "url": "classes/App-Http-Controllers-AuthController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\HomeController",
            "name": "HomeController",
            "summary": "",
            "url": "classes/App-Http-Controllers-HomeController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\HomeController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020controller\u0020instance.",
            "url": "classes/App-Http-Controllers-HomeController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\HomeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Show\u0020the\u0020application\u0020dashboard.",
            "url": "classes/App-Http-Controllers-HomeController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Http-Kernel.html"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middleware",
            "name": "middleware",
            "summary": "The\u0020application\u0027s\u0020global\u0020HTTP\u0020middleware\u0020stack.",
            "url": "classes/App-Http-Kernel.html#property_middleware"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middlewareGroups",
            "name": "middlewareGroups",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware\u0020groups.",
            "url": "classes/App-Http-Kernel.html#property_middlewareGroups"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024routeMiddleware",
            "name": "routeMiddleware",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware.",
            "url": "classes/App-Http-Kernel.html#property_routeMiddleware"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate",
            "name": "Authenticate",
            "summary": "",
            "url": "classes/App-Http-Middleware-Authenticate.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate\u003A\u003AredirectTo\u0028\u0029",
            "name": "redirectTo",
            "summary": "Get\u0020the\u0020path\u0020the\u0020user\u0020should\u0020be\u0020redirected\u0020to\u0020when\u0020they\u0020are\u0020not\u0020authenticated.",
            "url": "classes/App-Http-Middleware-Authenticate.html#method_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies",
            "name": "EncryptCookies",
            "summary": "",
            "url": "classes/App-Http-Middleware-EncryptCookies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020cookies\u0020that\u0020should\u0020not\u0020be\u0020encrypted.",
            "url": "classes/App-Http-Middleware-EncryptCookies.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "name": "PreventRequestsDuringMaintenance",
            "summary": "",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020reachable\u0020while\u0020maintenance\u0020mode\u0020is\u0020enabled.",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated",
            "name": "RedirectIfAuthenticated",
            "summary": "",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings",
            "name": "TrimStrings",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrimStrings.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020attributes\u0020that\u0020should\u0020not\u0020be\u0020trimmed.",
            "url": "classes/App-Http-Middleware-TrimStrings.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts",
            "name": "TrustHosts",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustHosts.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts\u003A\u003Ahosts\u0028\u0029",
            "name": "hosts",
            "summary": "Get\u0020the\u0020host\u0020patterns\u0020that\u0020should\u0020be\u0020trusted.",
            "url": "classes/App-Http-Middleware-TrustHosts.html#method_hosts"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies",
            "name": "TrustProxies",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustProxies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024proxies",
            "name": "proxies",
            "summary": "The\u0020trusted\u0020proxies\u0020for\u0020this\u0020application.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_proxies"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "The\u0020headers\u0020that\u0020should\u0020be\u0020used\u0020to\u0020detect\u0020proxies.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_headers"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken",
            "name": "VerifyCsrfToken",
            "summary": "",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020excluded\u0020from\u0020CSRF\u0020verification.",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Resources\\BasketIndexResource",
            "name": "BasketIndexResource",
            "summary": "",
            "url": "classes/App-Http-Resources-BasketIndexResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\BasketIndexResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-BasketIndexResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\BasketResource",
            "name": "BasketResource",
            "summary": "",
            "url": "classes/App-Http-Resources-BasketResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\BasketResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-BasketResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\BasketShowResource",
            "name": "BasketShowResource",
            "summary": "",
            "url": "classes/App-Http-Resources-BasketShowResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\BasketShowResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-BasketShowResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ItemResource",
            "name": "ItemResource",
            "summary": "",
            "url": "classes/App-Http-Resources-ItemResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ItemResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ItemResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\MarketIndexResource",
            "name": "MarketIndexResource",
            "summary": "",
            "url": "classes/App-Http-Resources-MarketIndexResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\MarketIndexResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-MarketIndexResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\MarketResource",
            "name": "MarketResource",
            "summary": "",
            "url": "classes/App-Http-Resources-MarketResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\MarketResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-MarketResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\MarketShowResource",
            "name": "MarketShowResource",
            "summary": "",
            "url": "classes/App-Http-Resources-MarketShowResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\MarketShowResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-MarketShowResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ProductIndexResource",
            "name": "ProductIndexResource",
            "summary": "",
            "url": "classes/App-Http-Resources-ProductIndexResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ProductIndexResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ProductIndexResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ProductResource",
            "name": "ProductResource",
            "summary": "",
            "url": "classes/App-Http-Resources-ProductResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ProductResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ProductResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ShopIndexResource",
            "name": "ShopIndexResource",
            "summary": "",
            "url": "classes/App-Http-Resources-ShopIndexResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ShopIndexResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ShopIndexResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ShopResource",
            "name": "ShopResource",
            "summary": "",
            "url": "classes/App-Http-Resources-ShopResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ShopResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ShopResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ShopsBasketsItemsResource",
            "name": "ShopsBasketsItemsResource",
            "summary": "",
            "url": "classes/App-Http-Resources-ShopsBasketsItemsResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ShopsBasketsItemsResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ShopsBasketsItemsResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ShopsBasketsResource",
            "name": "ShopsBasketsResource",
            "summary": "",
            "url": "classes/App-Http-Resources-ShopsBasketsResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ShopsBasketsResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ShopsBasketsResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UnitIndexResource",
            "name": "UnitIndexResource",
            "summary": "",
            "url": "classes/App-Http-Resources-UnitIndexResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UnitIndexResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-UnitIndexResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UnitProductResource",
            "name": "UnitProductResource",
            "summary": "",
            "url": "classes/App-Http-Resources-UnitProductResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UnitProductResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-UnitProductResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UnitResource",
            "name": "UnitResource",
            "summary": "",
            "url": "classes/App-Http-Resources-UnitResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UnitResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-UnitResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UserResource",
            "name": "UserResource",
            "summary": "",
            "url": "classes/App-Http-Resources-UserResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UserResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-UserResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Models\\Basket",
            "name": "Basket",
            "summary": "",
            "url": "classes/App-Models-Basket.html"
        },                {
            "fqsen": "\\App\\Models\\Basket\u003A\u003Aitems\u0028\u0029",
            "name": "items",
            "summary": "Links\u0020the\u0020basket\u0020to\u0020it\u0027s\u0020items",
            "url": "classes/App-Models-Basket.html#method_items"
        },                {
            "fqsen": "\\App\\Models\\Basket\u003A\u003Ashop\u0028\u0029",
            "name": "shop",
            "summary": "Links\u0020the\u0020basket\u0020to\u0020it\u0027s\u0020shop.",
            "url": "classes/App-Models-Basket.html#method_shop"
        },                {
            "fqsen": "\\App\\Models\\Basket\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "Links\u0020the\u0020basket\u0020to\u0020it\u0027s\u0020user\u0020\u0028buyer\u0029",
            "url": "classes/App-Models-Basket.html#method_user"
        },                {
            "fqsen": "\\App\\Models\\Basket\u003A\u003ASTATUS_UNCONFIRMED",
            "name": "STATUS_UNCONFIRMED",
            "summary": "",
            "url": "classes/App-Models-Basket.html#constant_STATUS_UNCONFIRMED"
        },                {
            "fqsen": "\\App\\Models\\Basket\u003A\u003ASTATUS_CONFIRMED",
            "name": "STATUS_CONFIRMED",
            "summary": "",
            "url": "classes/App-Models-Basket.html#constant_STATUS_CONFIRMED"
        },                {
            "fqsen": "\\App\\Models\\Basket\u003A\u003ASTATUS_PREPARING",
            "name": "STATUS_PREPARING",
            "summary": "",
            "url": "classes/App-Models-Basket.html#constant_STATUS_PREPARING"
        },                {
            "fqsen": "\\App\\Models\\Basket\u003A\u003ASTATUS_READY",
            "name": "STATUS_READY",
            "summary": "",
            "url": "classes/App-Models-Basket.html#constant_STATUS_READY"
        },                {
            "fqsen": "\\App\\Models\\Basket\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Basket.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Item",
            "name": "Item",
            "summary": "",
            "url": "classes/App-Models-Item.html"
        },                {
            "fqsen": "\\App\\Models\\Item\u003A\u003Abasket\u0028\u0029",
            "name": "basket",
            "summary": "Links\u0020the\u0020item\u0020to\u0020it\u0027s\u0020basket",
            "url": "classes/App-Models-Item.html#method_basket"
        },                {
            "fqsen": "\\App\\Models\\Item\u003A\u003Aproduct\u0028\u0029",
            "name": "product",
            "summary": "Links\u0020the\u0020item\u0020to\u0020it\u0027s\u0020product",
            "url": "classes/App-Models-Item.html#method_product"
        },                {
            "fqsen": "\\App\\Models\\Item\u003A\u003ASTATUS_UNCONFIRMED",
            "name": "STATUS_UNCONFIRMED",
            "summary": "",
            "url": "classes/App-Models-Item.html#constant_STATUS_UNCONFIRMED"
        },                {
            "fqsen": "\\App\\Models\\Item\u003A\u003ASTATUS_CONFIRMED",
            "name": "STATUS_CONFIRMED",
            "summary": "",
            "url": "classes/App-Models-Item.html#constant_STATUS_CONFIRMED"
        },                {
            "fqsen": "\\App\\Models\\Item\u003A\u003ASTATUS_PREPARING",
            "name": "STATUS_PREPARING",
            "summary": "",
            "url": "classes/App-Models-Item.html#constant_STATUS_PREPARING"
        },                {
            "fqsen": "\\App\\Models\\Item\u003A\u003ASTATUS_READY",
            "name": "STATUS_READY",
            "summary": "",
            "url": "classes/App-Models-Item.html#constant_STATUS_READY"
        },                {
            "fqsen": "\\App\\Models\\Item\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Item.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Market",
            "name": "Market",
            "summary": "",
            "url": "classes/App-Models-Market.html"
        },                {
            "fqsen": "\\App\\Models\\Market\u003A\u003Ashops\u0028\u0029",
            "name": "shops",
            "summary": "Links\u0020the\u0020market\u0020to\u0020it\u0027s\u0020shops",
            "url": "classes/App-Models-Market.html#method_shops"
        },                {
            "fqsen": "\\App\\Models\\Market\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Market.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Product",
            "name": "Product",
            "summary": "",
            "url": "classes/App-Models-Product.html"
        },                {
            "fqsen": "\\App\\Models\\Product\u003A\u003Aitems\u0028\u0029",
            "name": "items",
            "summary": "Links\u0020the\u0020product\u0020to\u0020it\u0027s\u0020items",
            "url": "classes/App-Models-Product.html#method_items"
        },                {
            "fqsen": "\\App\\Models\\Product\u003A\u003Ashop\u0028\u0029",
            "name": "shop",
            "summary": "Links\u0020the\u0020product\u0020to\u0020it\u0027s\u0020shop",
            "url": "classes/App-Models-Product.html#method_shop"
        },                {
            "fqsen": "\\App\\Models\\Product\u003A\u003Aunits\u0028\u0029",
            "name": "units",
            "summary": "Links\u0020the\u0020product\u0020to\u0020it\u0027s\u0020units,\u0020each\u0020of\u0020them\u0020with\u0020an\u0020associated\u0020price",
            "url": "classes/App-Models-Product.html#method_units"
        },                {
            "fqsen": "\\App\\Models\\Product\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Product.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Shop",
            "name": "Shop",
            "summary": "",
            "url": "classes/App-Models-Shop.html"
        },                {
            "fqsen": "\\App\\Models\\Shop\u003A\u003Amarket\u0028\u0029",
            "name": "market",
            "summary": "Links\u0020the\u0020shop\u0020to\u0020it\u0027s\u0020market",
            "url": "classes/App-Models-Shop.html#method_market"
        },                {
            "fqsen": "\\App\\Models\\Shop\u003A\u003Abaskets\u0028\u0029",
            "name": "baskets",
            "summary": "Links\u0020the\u0020shop\u0020to\u0020it\u0027s\u0020baskets",
            "url": "classes/App-Models-Shop.html#method_baskets"
        },                {
            "fqsen": "\\App\\Models\\Shop\u003A\u003Aproducts\u0028\u0029",
            "name": "products",
            "summary": "Links\u0020the\u0020shop\u0020to\u0020it\u0027s\u0020products",
            "url": "classes/App-Models-Shop.html#method_products"
        },                {
            "fqsen": "\\App\\Models\\Shop\u003A\u003Asellers\u0028\u0029",
            "name": "sellers",
            "summary": "Links\u0020the\u0020shop\u0020to\u0020it\u0027s\u0020sellers",
            "url": "classes/App-Models-Shop.html#method_sellers"
        },                {
            "fqsen": "\\App\\Models\\Shop\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Shop.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Unit",
            "name": "Unit",
            "summary": "",
            "url": "classes/App-Models-Unit.html"
        },                {
            "fqsen": "\\App\\Models\\Unit\u003A\u003Aproducts\u0028\u0029",
            "name": "products",
            "summary": "Links\u0020the\u0020unit\u0020to\u0020it\u0027s\u0020products",
            "url": "classes/App-Models-Unit.html#method_products"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003Abaskets\u0028\u0029",
            "name": "baskets",
            "summary": "Links\u0020the\u0020user\u0020to\u0020its\u0020baskets",
            "url": "classes/App-Models-User.html#method_baskets"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003AownedShops\u0028\u0029",
            "name": "ownedShops",
            "summary": "Links\u0020the\u0020seller\u0020to\u0020it\u0027s\u0020owned\u0020shops",
            "url": "classes/App-Models-User.html#method_ownedShops"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003AdistributedBaskets\u0028\u0029",
            "name": "distributedBaskets",
            "summary": "Links\u0020the\u0020distributor\u0020to\u0020it\u0027s\u0020distributed\u0020baskets",
            "url": "classes/App-Models-User.html#method_distributedBaskets"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020arrays.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast\u0020to\u0020native\u0020types.",
            "url": "classes/App-Models-User.html#property_casts"
        },                {
            "fqsen": "\\Database\\Factories\\MarketFactory",
            "name": "MarketFactory",
            "summary": "",
            "url": "classes/Database-Factories-MarketFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\MarketFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-MarketFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\MarketFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "The\u0020name\u0020of\u0020the\u0020factory\u0027s\u0020corresponding\u0020model.",
            "url": "classes/Database-Factories-MarketFactory.html#property_model"
        },                {
            "fqsen": "\\Database\\Factories\\ProductFactory",
            "name": "ProductFactory",
            "summary": "",
            "url": "classes/Database-Factories-ProductFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\ProductFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-ProductFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\ProductFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "The\u0020name\u0020of\u0020the\u0020factory\u0027s\u0020corresponding\u0020model.",
            "url": "classes/Database-Factories-ProductFactory.html#property_model"
        },                {
            "fqsen": "\\Database\\Factories\\ShopFactory",
            "name": "ShopFactory",
            "summary": "",
            "url": "classes/Database-Factories-ShopFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\ShopFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-ShopFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\ShopFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "The\u0020name\u0020of\u0020the\u0020factory\u0027s\u0020corresponding\u0020model.",
            "url": "classes/Database-Factories-ShopFactory.html#property_model"
        },                {
            "fqsen": "\\Database\\Factories\\UnitFactory",
            "name": "UnitFactory",
            "summary": "",
            "url": "classes/Database-Factories-UnitFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UnitFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-UnitFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UnitFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "The\u0020name\u0020of\u0020the\u0020factory\u0027s\u0020corresponding\u0020model.",
            "url": "classes/Database-Factories-UnitFactory.html#property_model"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory",
            "name": "UserFactory",
            "summary": "",
            "url": "classes/Database-Factories-UserFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-UserFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Aunverified\u0028\u0029",
            "name": "unverified",
            "summary": "Indicate\u0020that\u0020the\u0020model\u0027s\u0020email\u0020address\u0020should\u0020be\u0020unverified.",
            "url": "classes/Database-Factories-UserFactory.html#method_unverified"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "The\u0020name\u0020of\u0020the\u0020factory\u0027s\u0020corresponding\u0020model.",
            "url": "classes/Database-Factories-UserFactory.html#property_model"
        },                {
            "fqsen": "\\CreateUsersTable",
            "name": "CreateUsersTable",
            "summary": "",
            "url": "classes/CreateUsersTable.html"
        },                {
            "fqsen": "\\CreateUsersTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateUsersTable.html#method_up"
        },                {
            "fqsen": "\\CreateUsersTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateUsersTable.html#method_down"
        },                {
            "fqsen": "\\CreatePasswordResetsTable",
            "name": "CreatePasswordResetsTable",
            "summary": "",
            "url": "classes/CreatePasswordResetsTable.html"
        },                {
            "fqsen": "\\CreatePasswordResetsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreatePasswordResetsTable.html#method_up"
        },                {
            "fqsen": "\\CreatePasswordResetsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreatePasswordResetsTable.html#method_down"
        },                {
            "fqsen": "\\CreateFailedJobsTable",
            "name": "CreateFailedJobsTable",
            "summary": "",
            "url": "classes/CreateFailedJobsTable.html"
        },                {
            "fqsen": "\\CreateFailedJobsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateFailedJobsTable.html#method_up"
        },                {
            "fqsen": "\\CreateFailedJobsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateFailedJobsTable.html#method_down"
        },                {
            "fqsen": "\\CreatePersonalAccessTokensTable",
            "name": "CreatePersonalAccessTokensTable",
            "summary": "",
            "url": "classes/CreatePersonalAccessTokensTable.html"
        },                {
            "fqsen": "\\CreatePersonalAccessTokensTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreatePersonalAccessTokensTable.html#method_up"
        },                {
            "fqsen": "\\CreatePersonalAccessTokensTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreatePersonalAccessTokensTable.html#method_down"
        },                {
            "fqsen": "\\CreateMarketsTable",
            "name": "CreateMarketsTable",
            "summary": "",
            "url": "classes/CreateMarketsTable.html"
        },                {
            "fqsen": "\\CreateMarketsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateMarketsTable.html#method_up"
        },                {
            "fqsen": "\\CreateMarketsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateMarketsTable.html#method_down"
        },                {
            "fqsen": "\\CreateShopsTable",
            "name": "CreateShopsTable",
            "summary": "",
            "url": "classes/CreateShopsTable.html"
        },                {
            "fqsen": "\\CreateShopsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateShopsTable.html#method_up"
        },                {
            "fqsen": "\\CreateShopsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateShopsTable.html#method_down"
        },                {
            "fqsen": "\\CreateProductsTable",
            "name": "CreateProductsTable",
            "summary": "",
            "url": "classes/CreateProductsTable.html"
        },                {
            "fqsen": "\\CreateProductsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateProductsTable.html#method_up"
        },                {
            "fqsen": "\\CreateProductsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateProductsTable.html#method_down"
        },                {
            "fqsen": "\\CreateUnitsTable",
            "name": "CreateUnitsTable",
            "summary": "",
            "url": "classes/CreateUnitsTable.html"
        },                {
            "fqsen": "\\CreateUnitsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateUnitsTable.html#method_up"
        },                {
            "fqsen": "\\CreateUnitsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateUnitsTable.html#method_down"
        },                {
            "fqsen": "\\CreateBasketsTable",
            "name": "CreateBasketsTable",
            "summary": "",
            "url": "classes/CreateBasketsTable.html"
        },                {
            "fqsen": "\\CreateBasketsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateBasketsTable.html#method_up"
        },                {
            "fqsen": "\\CreateBasketsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateBasketsTable.html#method_down"
        },                {
            "fqsen": "\\CreateItemsTable",
            "name": "CreateItemsTable",
            "summary": "",
            "url": "classes/CreateItemsTable.html"
        },                {
            "fqsen": "\\CreateItemsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateItemsTable.html#method_up"
        },                {
            "fqsen": "\\CreateItemsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateItemsTable.html#method_down"
        },                {
            "fqsen": "\\CreateProductUnitTable",
            "name": "CreateProductUnitTable",
            "summary": "",
            "url": "classes/CreateProductUnitTable.html"
        },                {
            "fqsen": "\\CreateProductUnitTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateProductUnitTable.html#method_up"
        },                {
            "fqsen": "\\CreateProductUnitTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateProductUnitTable.html#method_down"
        },                {
            "fqsen": "\\CreateShopOwnerTable",
            "name": "CreateShopOwnerTable",
            "summary": "",
            "url": "classes/CreateShopOwnerTable.html"
        },                {
            "fqsen": "\\CreateShopOwnerTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateShopOwnerTable.html#method_up"
        },                {
            "fqsen": "\\CreateShopOwnerTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateShopOwnerTable.html#method_down"
        },                {
            "fqsen": "\\AddPersonalDataToUsersTable",
            "name": "AddPersonalDataToUsersTable",
            "summary": "",
            "url": "classes/AddPersonalDataToUsersTable.html"
        },                {
            "fqsen": "\\AddPersonalDataToUsersTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddPersonalDataToUsersTable.html#method_up"
        },                {
            "fqsen": "\\AddPersonalDataToUsersTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddPersonalDataToUsersTable.html#method_down"
        },                {
            "fqsen": "\\AddImageToMarketsTable",
            "name": "AddImageToMarketsTable",
            "summary": "",
            "url": "classes/AddImageToMarketsTable.html"
        },                {
            "fqsen": "\\AddImageToMarketsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddImageToMarketsTable.html#method_up"
        },                {
            "fqsen": "\\AddImageToMarketsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddImageToMarketsTable.html#method_down"
        },                {
            "fqsen": "\\AddImageToShopsTable",
            "name": "AddImageToShopsTable",
            "summary": "",
            "url": "classes/AddImageToShopsTable.html"
        },                {
            "fqsen": "\\AddImageToShopsTable\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/AddImageToShopsTable.html#method_up"
        },                {
            "fqsen": "\\AddImageToShopsTable\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/AddImageToShopsTable.html#method_down"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder",
            "name": "DatabaseSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DatabaseSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Seed\u0020the\u0020application\u0027s\u0020database.",
            "url": "classes/Database-Seeders-DatabaseSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\MarketsTableSeeder",
            "name": "MarketsTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-MarketsTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\MarketsTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-MarketsTableSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\ProductsTableSeeder",
            "name": "ProductsTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-ProductsTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\ProductsTableSeeder\u003A\u003Ademo_products\u0028\u0029",
            "name": "demo_products",
            "summary": "",
            "url": "classes/Database-Seeders-ProductsTableSeeder.html#method_demo_products"
        },                {
            "fqsen": "\\Database\\Seeders\\ProductsTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-ProductsTableSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\ProductsTableSeeder\u003A\u003AmapUnits\u0028\u0029",
            "name": "mapUnits",
            "summary": "",
            "url": "classes/Database-Seeders-ProductsTableSeeder.html#method_mapUnits"
        },                {
            "fqsen": "\\Database\\Seeders\\ShopsTableSeeder",
            "name": "ShopsTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-ShopsTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\ShopsTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-ShopsTableSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\UnitsTableSeeder",
            "name": "UnitsTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-UnitsTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\UnitsTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-UnitsTableSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\UsersTableSeeder",
            "name": "UsersTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-UsersTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\UsersTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-UsersTableSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\ItemsTableSeeder",
            "name": "ItemsTableSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-ItemsTableSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\ItemsTableSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds\u0020for\u0020Baskets\/Items",
            "url": "classes/Database-Seeders-ItemsTableSeeder.html#method_run"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/app-http-controllers-api.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "namespaces/app-http-controllers-auth.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Http\\Resources",
            "name": "Resources",
            "summary": "",
            "url": "namespaces/app-http-resources.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\Database\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/database-factories.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Database\\Seeders",
            "name": "Seeders",
            "summary": "",
            "url": "namespaces/database-seeders.html"
        }            ]
);
